# Generated by Django 4.2.2 on 2023-10-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_category_is_active_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
        migrations.AddField(
            model_name='product',
            name='product_cat',
            field=models.ManyToManyField(to='myshop.category'),
        ),
    ]
